services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: django-backend-dev
    volumes:
      - ./backend/code:/backend/code
    env_file:
      - ./backend/.env.dev
#    environment:
#      - POSTGRES_HOST=db
#    depends_on:
#      - db
    ports:
      - "8000:8000"
volumes: